name: bmff
description: The package provides a library for reading ISO Base Media File Format (BMFF) files.
version: 1.3.1
homepage: https://github.com/CaiJingLong/bmff

environment:
  sdk: ">=2.12.0 <3.0.0"

# dependencies:
#   path: ^1.8.0

dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0
